### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by jklasdjklasdc** [pro470/Flow.Launcher.Plugin.komoflow#2]
[2024-12-26.txt](https://github.com/user-attachments/files/18254799/2024-12-26.txt)
Flow Launcher version: 1.19.4
OS Version: 22631.4037
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 12/26/2024 13:41:18
Exception:
komoflow Exception: 
Websites: https://github.com/pro470/Flow.Launcher.Plugin.komoflow
Author: pro470
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.komoflow\plugin\utils.py:545: SyntaxWarning: invalid escape sequence '\w'
  "-File", "plugin\windows_index.ps1",  # Path to the PowerShell script

 ---> System.IO.InvalidDataException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\Flow.Launcher.Plugin.komoflow\plugin\utils.py:545: SyntaxWarning: invalid escape sequence '\w'
  "-File", "plugin\windows_index.ps1",  # Path to the PowerShell script

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pro470** [comment]
I fixed it a long time ago but didn't push it sorry clone the repo or pull it should work now

**Comment by pro470** [comment]
Pushed new version too, so new release should be released shortly
